name: Deploy Django to AWS EC2 with Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

    - name: Sync and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
          cd /home/ubuntu/ai_webpage
          sudo chown -R $USER:$USER .git
          git config --global --add safe.directory /home/ubuntu/ai_webpage
          git pull origin main
        EOF
